import Head from 'next/head'

import Main from '@/components/Main'
import Layout from '@/components/Layout'
import { useEffect } from 'react';
export default function Home() {
  const scrollActive = () => {
    const sections = document.querySelectorAll('section[id]')
    const scrollDown = window.scrollY;
    sections.forEach((current) => {
      const sectionHeight = current.offsetHeight,
        sectionTop = current.offsetTop - 58,
        sectionId = current.getAttribute("id"),
        sectionsClass = document.querySelector(
          ".nav__menu span[href*=" + sectionId + "]"
        );
      if (scrollDown > sectionTop && scrollDown <= sectionTop + sectionHeight) {
        sectionsClass.classList.add("active-link");
      } else {
        sectionsClass.classList.remove("active-link");
      }
    });
  };


  useEffect(() => {

    window.addEventListener("scroll", scrollActive);
  }, [])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout offMenu={false}>
        <Main />
      </Layout>

    </>
  )
}
